import type { UnitLanguageClassificationMap } from "./types";

// Auto-classified K language classifications for k3-language-unit-02.
// Generated from the Language Classification Review tool using the default
// auto-classifier + errorSuggestions.ts (no reviewer overrides).
// 4 error items auto-resolved via errorSuggestions.ts → emitted as 9 target sentences + 1 keyword.

export const k3LanguageUnit02Classifications: UnitLanguageClassificationMap = {
  "pu-l2": {
    newKeywords: [
      { text: "week", source: "PU" },
      { text: "after", source: "PU" },
      { text: "before", source: "PU" },
      { text: "book club", source: "PU" },
      { text: "feed", source: "PU" },
      { text: "on (Wednesday(s))", source: "PU" },
      { text: "swimming pool", source: "PU" },
      { text: "swimsuit", source: "PU" },
      { text: "take turns", source: "PU" },
      { text: "(at the) weekend", source: "PU" },
    ],
    recycledKeywords: [
      { text: "sports and hobbies", source: "PU" },
      { text: "at home", source: "PU" },
      { text: "day", source: "PU" },
      { text: "favourite", source: "PU" },
      { text: "fish", source: "PU" },
      { text: "go for a swim", source: "PU" },
      { text: "need", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "play", source: "PU" },
      { text: "read", source: "PU" },
      { text: "sport", source: "PU" },
      { text: "today", source: "PU" },
      { text: "towel", source: "PU" },
      { text: "write", source: "PU" },
      { text: "So dol.", source: "PU" },
    ],
    targetSentences: [
      { text: "have got", source: "PU" },
      { text: "I love ...-ing", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "new", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
      { text: "classroom", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["book","crayon","teacher","bag","classroom","pencil","school","rubber"] },
      { text: "school", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["book","crayon","teacher","bag","classroom","pencil","school","rubber"] },
    ],
  },
  "pu-l3": {
    newKeywords: [
      { text: "once/twice a day", source: "PU" },
      { text: "always", source: "PU" },
      { text: "often", source: "PU" },
      { text: "sometimes", source: "PU" },
      { text: "never", source: "PU" },
    ],
    recycledKeywords: [
      { text: "at home/school", source: "PU" },
      { text: "bird", source: "PU" },
      { text: "face", source: "PU" },
      { text: "feed", source: "PU" },
      { text: "fish", source: "PU" },
      { text: "here", source: "PU" },
      { text: "live", source: "PU" },
      { text: "(in the) morning/ afternoon/evening", source: "PU" },
      { text: "need", source: "PU" },
      { text: "on", source: "PU" },
      { text: "pet", source: "PU" },
      { text: "put", source: "PU" },
      { text: "table", source: "PU" },
      { text: "talk", source: "PU" },
      { text: "wash", source: "PU" },
      { text: "weekend", source: "PU" },
      { text: "can", source: "PU" },
      { text: "Let's...", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    targetSentences: [
      { text: "shelf How often... ?", source: "PU" },
      { text: "Do you ever... ?", source: "PU" },
      { text: "I don't think so.", source: "PU" },
      { text: "I don't know", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l4": {
    newKeywords: [
      { text: "often", source: "PU" },
      { text: "sometimes", source: "PU" },
      { text: "never", source: "PU" },
      { text: "at night", source: "PU" },
      { text: "late", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "sports and hobbies", source: "PU" },
      { text: "breakfast", source: "PU" },
      { text: "burger", source: "PU" },
      { text: "clean your teeth", source: "PU" },
      { text: "dinner", source: "PU" },
      { text: "feed", source: "PU" },
      { text: "fish", source: "PU" },
      { text: "go for a swim", source: "PU" },
      { text: "lunch", source: "PU" },
      { text: "once/twice a (week)", source: "PU" },
    ],
    targetSentences: [
      { text: "How often do you clean your teeth?", source: "PU" },
      { text: "I always clean them after breakfast.", source: "PU" },
      { text: "I have lunch and dinner.", source: "PU" },
      { text: "Do you ever get up late?", source: "PU" },
      { text: "No, I don't.", source: "PU" },
      { text: "I never get up late.", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
    ],
  },
  "pu-l5": {
    newKeywords: [
      { text: "go skating/shopping", source: "PU" },
      { text: "listen to a CD/ music", source: "PU" },
      { text: "read a comic", source: "PU" },
      { text: "watch a DVD/film", source: "PU" },
      { text: "write an email", source: "PU" },
    ],
    recycledKeywords: [
      { text: "sports and hobbies", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    targetSentences: [
      { text: "Do you ever ... 2", source: "PU" },
      { text: "How often do you... ?", source: "PU" },
    ],
    reviewIssues: [
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
    ],
  },
  "pu-l6": {
    newKeywords: [
      { text: "helmet", source: "PU" },
      { text: "roller skating", source: "PU" },
      { text: "rules", source: "PU" },
      { text: "skate (n", source: "PU" },
      { text: "v)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "birthday", source: "PU" },
      { text: "cupboard", source: "PU" },
      { text: "do (your) homework", source: "PU" },
      { text: "go shopping", source: "PU" },
      { text: "listen", source: "PU" },
      { text: "park", source: "PU" },
      { text: "present", source: "PU" },
      { text: "put", source: "PU" },
      { text: "street", source: "PU" },
      { text: "swimming pool", source: "PU" },
      { text: "talk", source: "PU" },
      { text: "wear", source: "PU" },
    ],
    targetSentences: [
      { text: "What must I do?", source: "PU" },
      { text: "You mustn't wear your skates in the house.", source: "PU" },
      { text: "You must put them in the cupboard.", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
      { text: "free time activities", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
      { text: "can/can't", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["can","must"] },
    ],
  },
  "pu-l7": {
    newKeywords: [
      { text: "accident", source: "PU" },
      { text: "body (bodies)", source: "PU" },
      { text: "elbow/knee pads", source: "PU" },
      { text: "exercise (n)", source: "PU" },
      { text: "gloves", source: "PU" },
      { text: "goggles", source: "PU" },
      { text: "healthy", source: "PU" },
      { text: "protect", source: "PU" },
      { text: "safe", source: "PU" },
    ],
    recycledKeywords: [
      { text: "clothes", source: "PU" },
      { text: "helmet", source: "PU" },
      { text: "wear", source: "PU" },
    ],
    reviewIssues: [
      { text: "free time activities", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
      { text: "parts of the body", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["ears","eyes","hair","mouth","legs","ear","arm","body","eye","face","feet","foot","hand","head","leg","nose","tail"] },
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
    ],
  },
  "pu-l8": {
    newKeywords: [
      { text: "bones", source: "PU" },
      { text: "do exercise", source: "PU" },
      { text: "exercise (v)", source: "PU" },
      { text: "horse riding", source: "PU" },
      { text: "(get) hot", source: "PU" },
      { text: "hurt", source: "PU" },
      { text: "muscles", source: "PU" },
      { text: "skin", source: "PU" },
      { text: "sun cream", source: "PU" },
      { text: "sweat (v)", source: "PU" },
      { text: "warm up", source: "PU" },
    ],
    recycledKeywords: [
      { text: "beach", source: "PU" },
      { text: "body", source: "PU" },
      { text: "boots", source: "PU" },
      { text: "drink", source: "PU" },
      { text: "helmet", source: "PU" },
      { text: "help", source: "PU" },
      { text: "look after", source: "PU" },
      { text: "move", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "play (sport)", source: "PU" },
      { text: "protect", source: "PU" },
      { text: "remember", source: "PU" },
      { text: "safe", source: "PU" },
      { text: "sun", source: "PU" },
      { text: "use", source: "PU" },
      { text: "water", source: "PU" },
      { text: "must", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
      { text: "free time activities", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
      { text: "parts of the body", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["ears","eyes","hair","mouth","legs","ear","arm","body","eye","face","feet","foot","hand","head","leg","nose","tail"] },
    ],
  },
  "pu-l9": {
    newKeywords: [
      { text: "alarm", source: "PU" },
      { text: "assembly hall", source: "PU" },
      { text: "blanket", source: "PU" },
      { text: "downstairs", source: "PU" },
      { text: "drive", source: "PU" },
      { text: "go to sleep", source: "PU" },
      { text: "leave (= go out)", source: "PU" },
      { text: "lights (= traffic lights)", source: "PU" },
      { text: "mirror", source: "PU" },
      { text: "now", source: "PU" },
      { text: "presentation", source: "PU" },
      { text: "shout", source: "PU" },
      { text: "suddenly", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "time (o'clock)", source: "PU" },
      { text: "bathroom", source: "PU" },
      { text: "breakfast", source: "PU" },
      { text: "chocolate", source: "PU" },
      { text: "classmate", source: "PU" },
      { text: "happy", source: "PU" },
      { text: "kitchen", source: "PU" },
      { text: "late", source: "PU" },
      { text: "milk", source: "PU" },
      { text: "shirt", source: "PU" },
      { text: "turn off", source: "PU" },
      { text: "use", source: "PU" },
      { text: "present simple", source: "PU" },
      { text: "want to", source: "PU" },
    ],
    targetSentences: [
      { text: "How often ... ?", source: "PU" },
      { text: "must/mustn't", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
      { text: "family", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["Dad","Mum","man","woman","boy","girl","family","friend","twins","brother","sister","pet","grandma","grandpa","teddy","father","mother","baby"] },
      { text: "parts of the body", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["ears","eyes","hair","mouth","legs","ear","arm","body","eye","face","feet","foot","hand","head","leg","nose","tail"] },
      { text: "fruit", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l10": {
    newKeywords: [
      { text: "action", source: "PU" },
      { text: "consequence", source: "PU" },
    ],
    recycledKeywords: [
      { text: "language from the story", source: "PU" },
      { text: "favourite", source: "PU" },
    ],
    reviewIssues: [
      { text: "days of the week", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["evening","morning","afternoon","today","yesterday"] },
    ],
  },
  "pu-l11": {
    recycledKeywords: [
      { text: "vocabulary from Units 1 and 2", source: "PU" },
      { text: "breakfast", source: "PU" },
      { text: "lunch", source: "PU" },
      { text: "dinner", source: "PU" },
      { text: "morning", source: "PU" },
      { text: "afternoon", source: "PU" },
      { text: "evening", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    reviewIssues: [
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
    ],
  },
  "pu-l12": {
    recycledKeywords: [
      { text: "unit language", source: "PU" },
      { text: "scene", source: "PU" },
    ],
  },
};
