import type { UnitLanguageClassificationMap } from "./types";

// Auto-classified K language classifications for k3-language-unit-07.
// Generated from the Language Classification Review tool using the default
// auto-classifier + errorSuggestions.ts (no reviewer overrides).
// 8 error items auto-resolved via errorSuggestions.ts → emitted as 20 target sentences.

export const k3LanguageUnit07Classifications: UnitLanguageClassificationMap = {
  "pu-l2": {
    newKeywords: [
      { text: "bottle", source: "PU" },
      { text: "bowl", source: "PU" },
      { text: "cheese", source: "PU" },
      { text: "cooking", source: "PU" },
      { text: "cup", source: "PU" },
      { text: "glass", source: "PU" },
      { text: "pasta", source: "PU" },
      { text: "plate", source: "PU" },
      { text: "salad", source: "PU" },
      { text: "sandwich", source: "PU" },
      { text: "soup", source: "PU" },
      { text: "vegetables", source: "PU" },
      { text: "a (cup) of (hot chocolate)", source: "PU" },
      { text: "kind (What kind of... ?)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "class", source: "PU" },
      { text: "cold", source: "PU" },
      { text: "drink (n)", source: "PU" },
      { text: "hot", source: "PU" },
      { text: "hot chocolate", source: "PU" },
      { text: "lunch", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "thank you.", source: "PU" },
    ],
    targetSentences: [
      { text: "Can you ... ?", source: "PU" },
      { text: "Do you like ... ?", source: "PU" },
      { text: "have got", source: "PU" },
      { text: "Would you like ...?", source: "PU" },
      { text: "Yes, please.", source: "PU" },
      { text: "No, thank you.", source: "PU" },
      { text: "No, thank you.", source: "PU" },
    ],
    reviewIssues: [
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l3": {
    newKeywords: [
      { text: "ate", source: "PU" },
      { text: "drank", source: "PU" },
      { text: "got", source: "PU" },
      { text: "had", source: "PU" },
      { text: "made", source: "PU" },
      { text: "put", source: "PU" },
      { text: "saw", source: "PU" },
      { text: "went", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "food and things for serving food", source: "PU" },
      { text: "afternoon", source: "PU" },
      { text: "at school", source: "PU" },
      { text: "bring", source: "PU" },
      { text: "car", source: "PU" },
      { text: "cold", source: "PU" },
      { text: "cooking", source: "PU" },
      { text: "favourite", source: "PU" },
      { text: "go shopping", source: "PU" },
      { text: "kind (n)", source: "PU" },
      { text: "kitchen", source: "PU" },
      { text: "nice", source: "PU" },
      { text: "only", source: "PU" },
      { text: "sock", source: "PU" },
      { text: "yesterday", source: "PU" },
      { text: "can", source: "PU" },
      { text: "telling the time", source: "PU" },
    ],
    targetSentences: [
      { text: "Did they (eat)?", source: "PU" },
      { text: "Yes, they did.", source: "PU" },
      { text: "No, they didn't.", source: "PU" },
      { text: "No, they didn't.", source: "PU" },
      { text: "They didn't.", source: "PU" },
      { text: "I didn't (see).", source: "PU" },
      { text: "What did you (put in the soup)?", source: "PU" },
    ],
    reviewIssues: [
      { text: "classroom", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["book","crayon","teacher","bag","classroom","pencil","school","rubber"] },
      { text: "home", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["café","home","school","house","shop","beach","town","park","zoo","world"] },
    ],
  },
  "pu-l4": {
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "places", source: "PU" },
      { text: "drink (n)", source: "PU" },
      { text: "hot", source: "PU" },
      { text: "last", source: "PU" },
      { text: "(have) lunch", source: "PU" },
      { text: "picnic", source: "PU" },
      { text: "weekend", source: "PU" },
      { text: "irregular past simple forms", source: "PU" },
    ],
    targetSentences: [
      { text: "I went swimming last Saturday.", source: "PU" },
      { text: "I didn't go shopping yesterday.", source: "PU" },
      { text: "Did you go to the park?", source: "PU" },
      { text: "Yes, I did.", source: "PU" },
      { text: "No, I didn't.", source: "PU" },
      { text: "No, I didn't.", source: "PU" },
      { text: "I didn't. (the) same", source: "PU" },
      { text: "What about ... ?", source: "PU" },
    ],
    reviewIssues: [
      { text: "animals", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["bird","cat","animals","rabbit","animal","cow","sheep","monster","dog","elephant","flamingo","frog","toad","duck","horse","mouse","bear","crocodile","monkey","snake","tiger","lion"] },
      { text: "family", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["Dad","Mum","man","woman","boy","girl","family","friend","twins","brother","sister","pet","grandma","grandpa","teddy","father","mother","baby"] },
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l5": {
    newKeywords: [
      { text: "boil", source: "PU" },
      { text: "carry", source: "PU" },
      { text: "cook", source: "PU" },
      { text: "cry", source: "PU" },
      { text: "cut", source: "PU" },
      { text: "drop", source: "PU" },
      { text: "fry", source: "PU" },
      { text: "wash", source: "PU" },
    ],
    recycledKeywords: [
      { text: "food and things for serving food", source: "PU" },
      { text: "all right", source: "PU" },
      { text: "dinner", source: "PU" },
      { text: "hat", source: "PU" },
      { text: "help", source: "PU" },
      { text: "kitchen", source: "PU" },
      { text: "late", source: "PU" },
      { text: "start", source: "PU" },
      { text: "stop", source: "PU" },
      { text: "wear", source: "PU" },
      { text: "mustn't", source: "PU" },
    ],
    targetSentences: [
      { text: "Can you (try this)? imperatives", source: "PU" },
    ],
    reviewIssues: [
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l6": {
    recycledKeywords: [
      { text: "actions in the kitchen", source: "PU" },
      { text: "past simple questions", source: "PU" },
    ],
    targetSentences: [
      { text: "like — I liked cooking them!", source: "PU" },
      { text: "fry — I fried the onions.", source: "PU" },
      { text: "stop/start — I stopped because you started asking me questions.", source: "PU" },
    ],
    reviewIssues: [
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l7": {
    newKeywords: [
      { text: "broccoli", source: "PU" },
      { text: "cauliflower", source: "PU" },
      { text: "delicious", source: "PU" },
      { text: "grow", source: "PU" },
      { text: "lettuce", source: "PU" },
      { text: "pepper", source: "PU" },
      { text: "pod", source: "PU" },
      { text: "spinach", source: "PU" },
    ],
    recycledKeywords: [
      { text: "cold", source: "PU" },
      { text: "cook (v)", source: "PU" },
      { text: "eat", source: "PU" },
      { text: "flower", source: "PU" },
      { text: "grass", source: "PU" },
      { text: "kind (n)", source: "PU" },
      { text: "leaves", source: "PU" },
      { text: "part", source: "PU" },
      { text: "plant (n)", source: "PU" },
      { text: "seed", source: "PU" },
      { text: "vegetables", source: "PU" },
    ],
    reviewIssues: [
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
      { text: "fruit", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l8": {
    newKeywords: [
      { text: "aloe vera", source: "PU" },
      { text: "coffee", source: "PU" },
      { text: "cotton", source: "PU" },
      { text: "flour", source: "PU" },
      { text: "medicine", source: "PU" },
      { text: "sauce", source: "PU" },
      { text: "tea", source: "PU" },
      { text: "wheat", source: "PU" },
    ],
    recycledKeywords: [
      { text: "beautiful", source: "PU" },
      { text: "chair", source: "PU" },
      { text: "clothes", source: "PU" },
      { text: "eat", source: "PU" },
      { text: "give", source: "PU" },
      { text: "important", source: "PU" },
      { text: "make", source: "PU" },
      { text: "need", source: "PU" },
      { text: "oxygen", source: "PU" },
      { text: "paper", source: "PU" },
      { text: "plant", source: "PU" },
      { text: "protect", source: "PU" },
      { text: "suncream", source: "PU" },
      { text: "table", source: "PU" },
      { text: "tree", source: "PU" },
      { text: "use", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    reviewIssues: [
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
    ],
  },
  "pu-l9": {
    newKeywords: [
      { text: "café", source: "PU" },
      { text: "dream", source: "PU" },
      { text: "ill", source: "PU" },
      { text: "lovely", source: "PU" },
      { text: "waiter", source: "PU" },
      { text: "wash the dishes", source: "PU" },
    ],
    recycledKeywords: [
      { text: "actions in the kitchen", source: "PU" },
      { text: "food and things for serving food", source: "PU" },
      { text: "bear", source: "PU" },
      { text: "beautiful", source: "PU" },
      { text: "cook (n", source: "PU" },
      { text: "v)", source: "PU" },
      { text: "famous", source: "PU" },
      { text: "job", source: "PU" },
      { text: "kitchen", source: "PU" },
      { text: "lunch", source: "PU" },
      { text: "practise", source: "PU" },
      { text: "shout", source: "PU" },
      { text: "TV show", source: "PU" },
      { text: "wash", source: "PU" },
      { text: "well", source: "PU" },
      { text: "past simple", source: "PU" },
    ],
    targetSentences: [
      { text: "How about... ?", source: "PU" },
    ],
  },
  "pu-l10": {
    newKeywords: [
      { text: "give up", source: "PU" },
    ],
    recycledKeywords: [
      { text: "language from the story", source: "PU" },
      { text: "like (Are you like Sonny?)", source: "PU" },
    ],
  },
  "pu-l11": {
    recycledKeywords: [
      { text: "actions", source: "PU" },
      { text: "clothes", source: "PU" },
      { text: "food and things we use to serve food", source: "PU" },
      { text: "weather", source: "PU" },
    ],
    reviewIssues: [
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l12": {
    recycledKeywords: [
      { text: "unit language", source: "PU" },
    ],
  },
};
