import type { UnitLanguageClassificationMap } from "./types";

// Auto-classified K language classifications for k3-language-unit-08.
// Generated from the Language Classification Review tool using the default
// auto-classifier + errorSuggestions.ts (no reviewer overrides).
// 3 error items auto-resolved via errorSuggestions.ts → emitted as 10 target sentences + 1 keyword.

export const k3LanguageUnit08Classifications: UnitLanguageClassificationMap = {
  "pu-l2": {
    newKeywords: [
      { text: "carpark", source: "PU" },
      { text: "city centre", source: "PU" },
      { text: "funfair", source: "PU" },
      { text: "map", source: "PU" },
      { text: "plan (v)", source: "PU" },
      { text: "ride (n)", source: "PU" },
      { text: "road", source: "PU" },
      { text: "station", source: "PU" },
      { text: "ticket", source: "PU" },
      { text: "trip", source: "PU" },
      { text: "numbers 21-30", source: "PU" },
      { text: "adventure", source: "PU" },
      { text: "buy,catch (a bus/train)", source: "PU" },
      { text: "drive (n", source: "PU" },
      { text: "v)", source: "PU" },
      { text: "get off", source: "PU" },
      { text: "get on", source: "PU" },
      { text: "website", source: "PU" },
    ],
    recycledKeywords: [
      { text: "numbers 1-20", source: "PU" },
      { text: "places", source: "PU" },
      { text: "vehicles", source: "PU" },
      { text: "bus stop", source: "PU" },
      { text: "countryside", source: "PU" },
      { text: "have a picnic", source: "PU" },
      { text: "near", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "comparative adjectives", source: "PU" },
      { text: "must", source: "PU" },
    ],
    targetSentences: [
      { text: "Canwe... ?", source: "PU" },
    ],
  },
  "pu-l3": {
    newKeywords: [
      { text: "bought", source: "PU" },
      { text: "brought", source: "PU" },
      { text: "came", source: "PU" },
      { text: "chose", source: "PU" },
      { text: "drove", source: "PU" },
      { text: "fed", source: "PU" },
      { text: "found", source: "PU" },
      { text: "gave", source: "PU" },
      { text: "hid", source: "PU" },
      { text: "lost", source: "PU" },
      { text: "rode", source: "PU" },
      { text: "sat", source: "PU" },
      { text: "slept", source: "PU" },
      { text: "stood", source: "PU" },
      { text: "told", source: "PU" },
      { text: "took", source: "PU" },
      { text: "wore", source: "PU" },
      { text: "hungry", source: "PU" },
    ],
    recycledKeywords: [
      { text: "adventure", source: "PU" },
      { text: "beach", source: "PU" },
      { text: "behind", source: "PU" },
      { text: "countryside", source: "PU" },
      { text: "cousin", source: "PU" },
      { text: "different", source: "PU" },
      { text: "farm", source: "PU" },
      { text: "favourite colour", source: "PU" },
      { text: "forest", source: "PU" },
      { text: "hat", source: "PU" },
      { text: "last (year)", source: "PU" },
      { text: "lorry", source: "PU" },
      { text: "on holiday", source: "PU" },
      { text: "this (morning)", source: "PU" },
      { text: "vegetables", source: "PU" },
      { text: "past simple", source: "PU" },
      { text: "was", source: "PU" },
      { text: "were", source: "PU" },
    ],
    targetSentences: [
      { text: "ShalllI... ?", source: "PU" },
    ],
  },
  "pu-l4": {
    newKeywords: [
      { text: "huge", source: "PU" },
    ],
    recycledKeywords: [
      { text: "day trips", source: "PU" },
      { text: "chocolate cake", source: "PU" },
      { text: "draw a picture", source: "PU" },
      { text: "scariest", source: "PU" },
      { text: "take a photo", source: "PU" },
      { text: "irregular past simple forms", source: "PU" },
    ],
    targetSentences: [
      { text: "find — I found my old hat.", source: "PU" },
      { text: "lose — I lost my cousin in the forest.", source: "PU" },
      { text: "buy — He bought it last year.", source: "PU" },
      { text: "come — We came to the farm last year.", source: "PU" },
    ],
  },
  "pu-l5": {
    newKeywords: [
      { text: "bus station", source: "PU" },
      { text: "café", source: "PU" },
      { text: "cinema", source: "PU" },
      { text: "hospital", source: "PU" },
      { text: "library", source: "PU" },
      { text: "market", source: "PU" },
      { text: "shopping centre", source: "PU" },
      { text: "sports centre", source: "PU" },
      { text: "square", source: "PU" },
      { text: "supermarket", source: "PU" },
      { text: "swimming pool", source: "PU" },
      { text: "numbers 31-100", source: "PU" },
    ],
    recycledKeywords: [
      { text: "day trips", source: "PU" },
      { text: "numbers 1-30", source: "PU" },
      { text: "book", source: "PU" },
      { text: "bus", source: "PU" },
      { text: "clothes", source: "PU" },
      { text: "film", source: "PU" },
      { text: "go for a swim", source: "PU" },
      { text: "park", source: "PU" },
      { text: "play tennis", source: "PU" },
      { text: "pretty", source: "PU" },
      { text: "shop", source: "PU" },
      { text: "vegetables", source: "PU" },
      { text: "irregular past simple forms", source: "PU" },
    ],
    reviewIssues: [
      { text: "food", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["fish","banana","watermelon","fruit","burger","egg","rice","food","breakfast","chicken","milk","water","lunch","juice","ice cream","bread","cake","chocolate","apple","dinner"] },
      { text: "home", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["café","home","school","house","shop","beach","town","park","zoo","world"] },
    ],
  },
  "pu-l6": {
    recycledKeywords: [
      { text: "places in town", source: "PU" },
      { text: "clean your bedroom", source: "PU" },
      { text: "do your homework", source: "PU" },
      { text: "help at home", source: "PU" },
      { text: "make your bed", source: "PU" },
      { text: "make your breakfast", source: "PU" },
      { text: "plate", source: "PU" },
      { text: "ride (n)", source: "PU" },
      { text: "wash", source: "PU" },
      { text: "wear (glasses)", source: "PU" },
    ],
    targetSentences: [
      { text: "I have to see the eye doctor at the hospital.", source: "PU" },
      { text: "My brother has to wear glasses.", source: "PU" },
      { text: "Do you have to wear glasses?", source: "PU" },
      { text: "Yes, I do.", source: "PU" },
      { text: "No, I don't.", source: "PU" },
      { text: "No, I don't.", source: "PU" },
      { text: "I don't.", source: "PU" },
    ],
  },
  "pu-l7": {
    newKeywords: [
      { text: "across", source: "PU" },
      { text: "bench", source: "PU" },
      { text: "cross (the road)", source: "PU" },
      { text: "hold (someone's) hand", source: "PU" },
      { text: "litter bin", source: "PU" },
      { text: "pavement", source: "PU" },
      { text: "pedestrian crossing", source: "PU" },
      { text: "road sign", source: "PU" },
      { text: "safety", source: "PU" },
      { text: "street lamp", source: "PU" },
      { text: "traffic lights", source: "PU" },
    ],
    recycledKeywords: [
      { text: "places in town", source: "PU" },
      { text: "vehicles", source: "PU" },
      { text: "always", source: "PU" },
      { text: "ball", source: "PU" },
      { text: "carry", source: "PU" },
      { text: "grown-up (n)", source: "PU" },
      { text: "listen", source: "PU" },
      { text: "look", source: "PU" },
      { text: "play", source: "PU" },
      { text: "road", source: "PU" },
      { text: "safe", source: "PU" },
      { text: "stop", source: "PU" },
      { text: "wait", source: "PU" },
      { text: "walk", source: "PU" },
      { text: "imperatives", source: "PU" },
    ],
  },
  "pu-l8": {
    recycledKeywords: [
      { text: "bench", source: "PU" },
      { text: "cross (the road)", source: "PU" },
      { text: "hold (someone's) hand", source: "PU" },
      { text: "litter bin", source: "PU" },
      { text: "pavement", source: "PU" },
      { text: "pedestrian crossing", source: "PU" },
      { text: "road sign", source: "PU" },
      { text: "safe", source: "PU" },
      { text: "street lamp", source: "PU" },
      { text: "traffic lights", source: "PU" },
      { text: "imperatives", source: "PU" },
    ],
    targetSentences: [
      { text: "must/mustn't", source: "PU" },
    ],
    reviewIssues: [
      { text: "prepositions of place", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["under","in","next to","on","behind","between","in front of"] },
    ],
  },
  "pu-l9": {
    newKeywords: [
      { text: "believe", source: "PU" },
      { text: "buddy", source: "PU" },
      { text: "driver", source: "PU" },
      { text: "heard", source: "PU" },
      { text: "(higher) and (higher)", source: "PU" },
      { text: "kindly", source: "PU" },
      { text: "seat", source: "PU" },
      { text: "seatbelt", source: "PU" },
      { text: "thought", source: "PU" },
    ],
    recycledKeywords: [
      { text: "places in town", source: "PU" },
      { text: "catch (the bus)", source: "PU" },
      { text: "close", source: "PU" },
      { text: "dream", source: "PU" },
      { text: "first", source: "PU" },
      { text: "funfair", source: "PU" },
      { text: "get ready", source: "PU" },
      { text: "late", source: "PU" },
      { text: "open", source: "PU" },
      { text: "push", source: "PU" },
      { text: "put on", source: "PU" },
      { text: "ride", source: "PU" },
      { text: "smile", source: "PU" },
      { text: "Don't worry", source: "PU" },
      { text: "have to", source: "PU" },
      { text: "past simple", source: "PU" },
    ],
    reviewIssues: [
      { text: "adjectives", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["new","nice","big","small","long","short","beautiful","dirty","old","clean","hot","ugly","cold","pretty","fat","tall","thin"] },
      { text: "colours", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["blue","green","orange","purple","red","yellow","black","brown"] },
      { text: "prepositions", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["under","in","next to","on","behind","between","in front of"] },
    ],
  },
  "pu-l10": {
    newKeywords: [
      { text: "optimistic", source: "PU" },
    ],
    recycledKeywords: [
      { text: "language from the story", source: "PU" },
    ],
  },
  "pu-l11": {
    recycledKeywords: [
      { text: "clothes", source: "PU" },
      { text: "countryside", source: "PU" },
      { text: "food and drink", source: "PU" },
      { text: "places in town", source: "PU" },
      { text: "bookshop", source: "PU" },
    ],
    reviewIssues: [
      { text: "colours", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["blue","green","orange","purple","red","yellow","black","brown"] },
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l12": {
    recycledKeywords: [
      { text: "unit language", source: "PU" },
    ],
  },
};
