import type { UnitLanguageClassificationMap } from "./types";

// Auto-classified K language classifications for k3-language-unit-01.
// Generated from the Language Classification Review tool using the default
// auto-classifier + errorSuggestions.ts (no reviewer overrides).
// 5 error items auto-resolved via errorSuggestions.ts → emitted as 6 target sentences.

export const k3LanguageUnit01Classifications: UnitLanguageClassificationMap = {
  "pu-l2": {
    newKeywords: [
      { text: "countryside", source: "PU" },
      { text: "field", source: "PU" },
      { text: "forest", source: "PU" },
      { text: "grass", source: "PU" },
      { text: "ground", source: "PU" },
      { text: "lake", source: "PU" },
      { text: "leaf", source: "PU" },
      { text: "leaves", source: "PU" },
      { text: "mountain", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "river", source: "PU" },
      { text: "rock", source: "PU" },
      { text: "tractor", source: "PU" },
      { text: "farm", source: "PU" },
      { text: "go for a swim/walk", source: "PU" },
      { text: "move", source: "PU" },
      { text: "pretty", source: "PU" },
    ],
    recycledKeywords: [
      { text: "afternoon", source: "PU" },
      { text: "beautiful", source: "PU" },
      { text: "behind", source: "PU" },
      { text: "flower", source: "PU" },
      { text: "garden", source: "PU" },
      { text: "in front of", source: "PU" },
      { text: "next to", source: "PU" },
      { text: "nice", source: "PU" },
      { text: "play", source: "PU" },
      { text: "swim", source: "PU" },
      { text: "tree", source: "PU" },
      { text: "under", source: "PU" },
      { text: "can for requests", source: "PU" },
      { text: "love ...-ing", source: "PU" },
    ],
    targetSentences: [
      { text: "have got", source: "PU" },
      { text: "Let's ...", source: "PU" },
      { text: "There is/are", source: "PU" },
    ],
    reviewIssues: [
      { text: "colours", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["blue","green","orange","purple","red","yellow","black","brown"] },
    ],
  },
  "pu-l3": {
    newKeywords: [
      { text: "awake", source: "PU" },
      { text: "fat", source: "PU" },
      { text: "kitten", source: "PU" },
      { text: "naughty", source: "PU" },
      { text: "puppy (puppies)", source: "PU" },
      { text: "wash", source: "PU" },
      { text: "the one with (the short tail)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "baby (babies)", source: "PU" },
      { text: "ball", source: "PU" },
      { text: "drink", source: "PU" },
      { text: "eat", source: "PU" },
      { text: "look", source: "PU" },
      { text: "lunch", source: "PU" },
      { text: "open", source: "PU" },
      { text: "play", source: "PU" },
      { text: "sleep", source: "PU" },
      { text: "sock", source: "PU" },
    ],
    targetSentences: [
      { text: "have got", source: "PU" },
    ],
    reviewIssues: [
      { text: "adjectives", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["new","nice","big","small","long","short","beautiful","dirty","old","clean","hot","ugly","cold","pretty","fat","tall","thin"] },
      { text: "colours", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["blue","green","orange","purple","red","yellow","black","brown"] },
      { text: "parts of the body", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["ears","eyes","hair","mouth","legs","ear","arm","body","eye","face","feet","foot","hand","head","leg","nose","tail"] },
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l4": {
    newKeywords: [
      { text: "they aren't.", source: "PU" },
      { text: "clean (v)", source: "PU" },
      { text: "do homework", source: "PU" },
      { text: "put on", source: "PU" },
      { text: "scissors", source: "PU" },
      { text: "take off", source: "PU" },
    ],
    recycledKeywords: [
      { text: "sports and hobbies", source: "PU" },
      { text: "boots", source: "PU" },
      { text: "crayon", source: "PU" },
      { text: "drink", source: "PU" },
      { text: "eat", source: "PU" },
      { text: "hand", source: "PU" },
      { text: "ice cream", source: "PU" },
      { text: "kitchen", source: "PU" },
      { text: "lemonade", source: "PU" },
      { text: "wash", source: "PU" },
    ],
    targetSentences: [
      { text: "Are you reading a book?", source: "PU" },
      { text: "No, I'm not (reading a book).", source: "PU" },
      { text: "No, I'm not.", source: "PU" },
      { text: "I'm doing my homework.", source: "PU" },
      { text: "Is she playing tennis?", source: "PU" },
      { text: "Yes, please.", source: "PU" },
      { text: "Yes, she is.", source: "PU" },
      { text: "She's playing tennis.", source: "PU" },
      { text: "Are they putting on their boots?", source: "PU" },
      { text: "No, thank you.", source: "PU" },
      { text: "They're taking off their boots.", source: "PU" },
    ],
  },
  "pu-l5": {
    newKeywords: [
      { text: "get dressed", source: "PU" },
      { text: "get up", source: "PU" },
      { text: "have a shower", source: "PU" },
      { text: "have breakfast", source: "PU" },
      { text: "toothbrush", source: "PU" },
      { text: "toothpaste", source: "PU" },
      { text: "towel", source: "PU" },
      { text: "wake up", source: "PU" },
      { text: "clean your teeth", source: "PU" },
      { text: "(get) dry", source: "PU" },
      { text: "Time for us to...", source: "PU" },
    ],
    recycledKeywords: [
      { text: "food and drink", source: "PU" },
      { text: "sports and hobbies", source: "PU" },
      { text: "get", source: "PU" },
      { text: "go", source: "PU" },
      { text: "run", source: "PU" },
      { text: "sit down", source: "PU" },
      { text: "imperatives", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    reviewIssues: [
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l6": {
    newKeywords: [
      { text: "finish", source: "PU" },
      { text: "go home", source: "PU" },
      { text: "go to bed", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "at school", source: "PU" },
      { text: "do homework", source: "PU" },
      { text: "go to school", source: "PU" },
      { text: "have lunch", source: "PU" },
      { text: "lesson", source: "PU" },
      { text: "start", source: "PU" },
      { text: "present simple questions and answers", source: "PU" },
    ],
    targetSentences: [
      { text: "What time do you get up?", source: "PU" },
      { text: "I get up at seven o'clock.", source: "PU" },
      { text: "What time does school finish?", source: "PU" },
      { text: "It finishes at four o'clock.", source: "PU" },
    ],
  },
  "pu-l7": {
    newKeywords: [
      { text: "air", source: "PU" },
      { text: "Earth", source: "PU" },
      { text: "gas", source: "PU" },
      { text: "important", source: "PU" },
      { text: "keep (someone) healthy", source: "PU" },
      { text: "look after", source: "PU" },
      { text: "need", source: "PU" },
      { text: "oxygen", source: "PU" },
      { text: "planet", source: "PU" },
      { text: "plant (n)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "clean (adj)", source: "PU" },
      { text: "water", source: "PU" },
    ],
    reviewIssues: [
      { text: "animal", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["bird","cat","animals","rabbit","animal","cow","sheep","monster","dog","elephant","flamingo","frog","toad","duck","horse","mouse","bear","crocodile","monkey","snake","tiger","lion"] },
    ],
  },
  "pu-l8": {
    newKeywords: [
      { text: "glass", source: "PU" },
      { text: "go out", source: "PU" },
      { text: "go shopping", source: "PU" },
      { text: "have a bath", source: "PU" },
      { text: "light (n)", source: "PU" },
      { text: "plastic", source: "PU" },
      { text: "plastic bag", source: "PU" },
      { text: "recycle", source: "PU" },
      { text: "save (water)", source: "PU" },
      { text: "tap", source: "PU" },
      { text: "turn off", source: "PU" },
      { text: "use", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "at home", source: "PU" },
      { text: "clean your teeth", source: "PU" },
      { text: "look after", source: "PU" },
      { text: "new", source: "PU" },
      { text: "paper", source: "PU" },
      { text: "water", source: "PU" },
      { text: "imperatives", source: "PU" },
    ],
  },
  "pu-l9": {
    newKeywords: [
      { text: "come/go back", source: "PU" },
      { text: "every day", source: "PU" },
      { text: "fall", source: "PU" },
      { text: "fast", source: "PU" },
      { text: "feel (sad)", source: "PU" },
      { text: "last (adj)", source: "PU" },
      { text: "move", source: "PU" },
      { text: "race (n)", source: "PU" },
      { text: "win", source: "PU" },
    ],
    recycledKeywords: [
      { text: "daily routines", source: "PU" },
      { text: "field", source: "PU" },
      { text: "fun", source: "PU" },
      { text: "ground", source: "PU" },
      { text: "happy", source: "PU" },
      { text: "help", source: "PU" },
      { text: "leaves", source: "PU" },
      { text: "leg", source: "PU" },
      { text: "nose", source: "PU" },
      { text: "play", source: "PU" },
      { text: "puppy", source: "PU" },
      { text: "river", source: "PU" },
      { text: "rock", source: "PU" },
      { text: "run", source: "PU" },
      { text: "sad", source: "PU" },
      { text: "sister", source: "PU" },
      { text: "stand", source: "PU" },
      { text: "stop", source: "PU" },
      { text: "imperatives", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    targetSentences: [
      { text: "I'm sorry", source: "PU" },
      { text: "Let's ...", source: "PU" },
    ],
    reviewIssues: [
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l10": {
    newKeywords: [
      { text: "support", source: "PU" },
      { text: "supportive", source: "PU" },
    ],
    recycledKeywords: [
      { text: "language from the poem", source: "PU" },
    ],
  },
  "pu-l11": {
    newKeywords: [
      { text: "farmer", source: "PU" },
      { text: "have a picnic", source: "PU" },
      { text: "sandwich(es)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "countryside", source: "PU" },
      { text: "food and drink", source: "PU" },
      { text: "tap", source: "PU" },
      { text: "tree", source: "PU" },
      { text: "wash (her) hands/boots", source: "PU" },
      { text: "Here...", source: "PU" },
    ],
    targetSentences: [
      { text: "have got", source: "PU" },
      { text: "There is/are", source: "PU" },
    ],
    reviewIssues: [
      { text: "animals", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["bird","cat","animals","rabbit","animal","cow","sheep","monster","dog","elephant","flamingo","frog","toad","duck","horse","mouse","bear","crocodile","monkey","snake","tiger","lion"] },
      { text: "prepositions of place", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["under","in","next to","on","behind","between","in front of"] },
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l12": {
    recycledKeywords: [
      { text: "unit language", source: "PU" },
    ],
  },
};
