import type { UnitLanguageClassificationMap } from "./types";

// Auto-classified K language classifications for k3-language-unit-04.
// Generated from the Language Classification Review tool using the default
// auto-classifier + errorSuggestions.ts (no reviewer overrides).
// 3 error items auto-resolved via errorSuggestions.ts → emitted as 9 target sentences.

export const k3LanguageUnit04Classifications: UnitLanguageClassificationMap = {
  "pu-l2": {
    newKeywords: [
      { text: "aunt", source: "PU" },
      { text: "cousin", source: "PU" },
      { text: "daughter", source: "PU" },
      { text: "granddaughter", source: "PU" },
      { text: "grandparents", source: "PU" },
      { text: "grandson", source: "PU" },
      { text: "grown-up (n)", source: "PU" },
      { text: "parents", source: "PU" },
      { text: "son", source: "PU" },
      { text: "uncle", source: "PU" },
      { text: "at the front", source: "PU" },
    ],
    recycledKeywords: [
      { text: "baby", source: "PU" },
      { text: "brother", source: "PU" },
      { text: "children", source: "PU" },
      { text: "(grand)father", source: "PU" },
      { text: "(grand)mother", source: "PU" },
      { text: "sister", source: "PU" },
      { text: "smile", source: "PU" },
      { text: "stand", source: "PU" },
      { text: "tall", source: "PU" },
      { text: "imperatives", source: "PU" },
    ],
    reviewIssues: [
      { text: "prepositions of place", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["under","in","next to","on","behind","between","in front of"] },
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l3": {
    newKeywords: [
      { text: "clever", source: "PU" },
    ],
    recycledKeywords: [
      { text: "extended family", source: "PU" },
      { text: "physical descriptions", source: "PU" },
      { text: "baby", source: "PU" },
      { text: "living room", source: "PU" },
      { text: "photo", source: "PU" },
      { text: "Sorry", source: "PU" },
    ],
    targetSentences: [
      { text: "You're right.", source: "PU" },
    ],
    reviewIssues: [
      { text: "adjectives", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["new","nice","big","small","long","short","beautiful","dirty","old","clean","hot","ugly","cold","pretty","fat","tall","thin"] },
      { text: "parts of the body", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["ears","eyes","hair","mouth","legs","ear","arm","body","eye","face","feet","foot","hand","head","leg","nose","tail"] },
    ],
  },
  "pu-l4": {
    recycledKeywords: [
      { text: "extended family", source: "PU" },
      { text: "physical descriptions", source: "PU" },
      { text: "better", source: "PU" },
      { text: "puppy", source: "PU" },
      { text: "worse", source: "PU" },
    ],
    targetSentences: [
      { text: "Gracie's ears are long.", source: "PU" },
      { text: "They're longer than Shelly's ears.", source: "PU" },
      { text: "Those puppies are both fat.", source: "PU" },
      { text: "But the brown puppy's fatter than the white one.", source: "PU" },
      { text: "My cousin's hair is curly.", source: "PU" },
      { text: "It's curlier than my uncle's.", source: "PU" },
      { text: "Shelly's singing is bad.", source: "PU" },
      { text: "It's worse than Gracie's singing.", source: "PU" },
    ],
    reviewIssues: [
      { text: "adjectives", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["new","nice","big","small","long","short","beautiful","dirty","old","clean","hot","ugly","cold","pretty","fat","tall","thin"] },
    ],
  },
  "pu-l5": {
    newKeywords: [
      { text: "balcony", source: "PU" },
      { text: "basement", source: "PU" },
      { text: "downstairs", source: "PU" },
      { text: "(first/ second/third) floor", source: "PU" },
      { text: "inside", source: "PU" },
      { text: "lift (n)", source: "PU" },
      { text: "outside", source: "PU" },
      { text: "roof", source: "PU" },
      { text: "stairs", source: "PU" },
      { text: "upstairs", source: "PU" },
      { text: "town centre", source: "PU" },
      { text: "village", source: "PU" },
    ],
    recycledKeywords: [
      { text: "extended family", source: "PU" },
      { text: "rooms and objects in a house", source: "PU" },
      { text: "barn", source: "PU" },
      { text: "car", source: "PU" },
      { text: "flat", source: "PU" },
      { text: "flower", source: "PU" },
      { text: "garden", source: "PU" },
      { text: "guitar", source: "PU" },
      { text: "house", source: "PU" },
      { text: "in", source: "PU" },
      { text: "live", source: "PU" },
      { text: "on", source: "PU" },
      { text: "plant", source: "PU" },
      { text: "shower", source: "PU" },
      { text: "small", source: "PU" },
      { text: "up/down", source: "PU" },
    ],
    targetSentences: [
      { text: "have got", source: "PU" },
      { text: "There is/are ...", source: "PU" },
      { text: "Where do you live?", source: "PU" },
    ],
  },
  "pu-l6": {
    newKeywords: [
      { text: "mine", source: "PU" },
      { text: "yours", source: "PU" },
      { text: "hers", source: "PU" },
      { text: "his", source: "PU" },
      { text: "ours", source: "PU" },
      { text: "theirs", source: "PU" },
    ],
    recycledKeywords: [
      { text: "extended family", source: "PU" },
      { text: "comparative adjectives", source: "PU" },
      { text: "possessive 's and possessive adjectives", source: "PU" },
    ],
    targetSentences: [
      { text: "Whose is this?", source: "PU" },
    ],
    reviewIssues: [
      { text: "classroom objects", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["book","crayon","teacher","bag","classroom","pencil","school","rubber"] },
      { text: "home", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["café","home","school","house","shop","beach","town","park","zoo","world"] },
    ],
  },
  "pu-l7": {
    newKeywords: [
      { text: "afew", source: "PU" },
      { text: "complex", source: "PU" },
      { text: "different", source: "PU" },
      { text: "easier", source: "PU" },
      { text: "electricity", source: "PU" },
      { text: "energy", source: "PU" },
      { text: "machine", source: "PU" },
      { text: "make (something) work (= function)", source: "PU" },
      { text: "part (of a machine)", source: "PU" },
      { text: "pull", source: "PU" },
      { text: "push", source: "PU" },
      { text: "simple", source: "PU" },
      { text: "swing (n)", source: "PU" },
    ],
    recycledKeywords: [
      { text: "bike", source: "PU" },
      { text: "computer", source: "PU" },
      { text: "help (v)", source: "PU" },
      { text: "lots of need", source: "PU" },
      { text: "park", source: "PU" },
      { text: "use", source: "PU" },
      { text: "work (n)", source: "PU" },
    ],
    reviewIssues: [
      { text: "home", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["café","home","school","house","shop","beach","town","park","zoo","world"] },
      { text: "school", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["book","crayon","teacher","bag","classroom","pencil","school","rubber"] },
    ],
  },
  "pu-l8": {
    newKeywords: [
      { text: "dishwasher", source: "PU" },
      { text: "invent", source: "PU" },
      { text: "lay the table", source: "PU" },
      { text: "vacuum (v)", source: "PU" },
      { text: "vacuum cleaner", source: "PU" },
      { text: "washing machine", source: "PU" },
    ],
    recycledKeywords: [
      { text: "homes", source: "PU" },
      { text: "camera", source: "PU" },
      { text: "clean (v)", source: "PU" },
      { text: "clothes", source: "PU" },
      { text: "floor", source: "PU" },
      { text: "help", source: "PU" },
      { text: "lift (n)", source: "PU" },
      { text: "machine", source: "PU" },
      { text: "photo", source: "PU" },
      { text: "take", source: "PU" },
      { text: "up/down", source: "PU" },
      { text: "use", source: "PU" },
      { text: "wash", source: "PU" },
      { text: "work (n)", source: "PU" },
    ],
    targetSentences: [
      { text: "How often do you (lay the table)?", source: "PU" },
    ],
    reviewIssues: [
      { text: "adverbs of frequency", originalSource: "recycled", issueType: "needs_extension", note: "", expansionHint: ["find","eat","jump","run","swim","walk","close","open","touch","draw","sing","help","look for","race","win","catch","clean","drink","sleep","stand","listen","share","rule","take","play","running","smile","dance","kick","wash","look","read","write","work","cry"] },
    ],
  },
  "pu-l9": {
    newKeywords: [
      { text: "ring (v)", source: "PU" },
      { text: "speaker phone", source: "PU" },
      { text: "text (v)", source: "PU" },
      { text: "usually", source: "PU" },
    ],
    recycledKeywords: [
      { text: "extended family", source: "PU" },
      { text: "homes", source: "PU" },
      { text: "birthday", source: "PU" },
      { text: "call", source: "PU" },
      { text: "chocolate cake", source: "PU" },
      { text: "dance", source: "PU" },
      { text: "everyone", source: "PU" },
      { text: "hat", source: "PU" },
      { text: "have fun", source: "PU" },
      { text: "late", source: "PU" },
      { text: "party", source: "PU" },
      { text: "robot", source: "PU" },
      { text: "sandwich(es)", source: "PU" },
      { text: "sing", source: "PU" },
      { text: "surprise", source: "PU" },
      { text: "town centre", source: "PU" },
      { text: "work", source: "PU" },
      { text: "comparative adjectives", source: "PU" },
      { text: "possessive pronouns", source: "PU" },
      { text: "present simple", source: "PU" },
    ],
    reviewIssues: [
      { text: "present continuous", originalSource: "recycled", issueType: "needs_extension", note: "" },
    ],
  },
  "pu-l10": {
    newKeywords: [
      { text: "excited", source: "PU" },
      { text: "feel", source: "PU" },
      { text: "worried", source: "PU" },
    ],
    recycledKeywords: [
      { text: "language from the story", source: "PU" },
      { text: "angry", source: "PU" },
      { text: "happy", source: "PU" },
      { text: "sad", source: "PU" },
    ],
  },
  "pu-l11": {
    recycledKeywords: [
      { text: "unit language", source: "PU" },
      { text: "best", source: "PU" },
    ],
  },
};
